# Generated by Django 5.0.7 on 2024-09-30 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_user'),
        ('facultyapp', '0002_blog_remove_bloglist_user_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('AOOP', 'Advanced Object Oriented Programming'), ('PFSD', 'Python Full Stack Development'), ('DBMS', 'DataBase Management System'), ('LAA', 'Linux Automation and Administration')], max_length=50)),
                ('section', models.CharField(choices=[('S11', 'Section11'), ('S12', 'Section12'), ('S13', 'Section13'), ('S14', 'Section14'), ('S15', 'Section15')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.studentlist')),
            ],
        ),
    ]
