# Generated by Django 5.0.7 on 2024-10-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0005_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
